cmake_minimum_required(VERSION 3.10.0)
project(hw_3 VERSION 0.1.0 LANGUAGES C)

add_subdirectory(A6)
add_subdirectory(A7)
add_subdirectory(A8)
add_subdirectory(A9)
add_subdirectory(A10)
add_subdirectory(A11)
add_subdirectory(A14)
add_subdirectory(A15)
add_subdirectory(A16)
add_subdirectory(A17)
add_subdirectory(A18)
add_subdirectory(A19)
