cmake_minimum_required(VERSION 3.10.0)
project(hw_6 VERSION 0.1.0 LANGUAGES C)

add_subdirectory(C1)
# add_subdirectory(C2)
# add_subdirectory(C3)
# add_subdirectory(C4)
# add_subdirectory(C5)
# add_subdirectory(C6)
# add_subdirectory(C7)
# add_subdirectory(C8)
# add_subdirectory(C9)
# add_subdirectory(C10)
# add_subdirectory(C11)
# add_subdirectory(C12)
# add_subdirectory(C13)
# add_subdirectory(C14)
# add_subdirectory(C15)
# add_subdirectory(C16)
# add_subdirectory(C17)
# add_subdirectory(C18)
# add_subdirectory(C19)
# add_subdirectory(C20)