cmake_minimum_required(VERSION 3.10.0)
project(hw_3 VERSION 0.1.0 LANGUAGES C)

add_subdirectory(B1)
add_subdirectory(B2)
add_subdirectory(B3)
add_subdirectory(B4)
add_subdirectory(B5)
add_subdirectory(B6)
add_subdirectory(B7)
add_subdirectory(B8)
add_subdirectory(B9)
add_subdirectory(B10)
add_subdirectory(B11)
add_subdirectory(B12)
add_subdirectory(B13)
add_subdirectory(B14)
add_subdirectory(B15)
add_subdirectory(B16)
add_subdirectory(B17)
add_subdirectory(B18)
add_subdirectory(B19)
add_subdirectory(B20)
add_subdirectory(B21)